
batch_size: 4
epochs: 180
train_dataset:
  - type: CFDataset
    start_epoch: 0
    dataset_root: E:/workspace/runtime/dataset/jingban
    anno_file: train.txt
    mode: train
    transforms:
      type: Compose
      augmentations: 
        - type: Resize
          base_size: 
          - 1024
          - 896
        - type: SmartCrop
          prob: 0.9
        - type: RandomHorizontalFlip
        - type: RandomVerticalFlip
        - type: RandomDistort
          brightness_range: 0.4
          contrast_range: 0.4
          saturation_range: 0.4
        - type: ToTensor
        - type: Normalize

val_dataset:
  type: CFDataset
  dataset_root: E:/workspace/runtime/dataset/jingban
  anno_file: val.txt
  mode: val
  transforms:
    type: Compose
    augmentations: 
      - type: Resize
        base_size: 
        - 1024
        - 896
      - type: ToTensor
      - type: Normalize
        

model:
  type: UNet
  num_classes: 2
  backbone: 
    type: ResNet18

optimizer:
  type: SGD
  lr: 1.0e-3
  momentum: 0.9
  weight_decay: 5.0e-4

lr_scheduler:
  - type: LinearLR
    start_factor: 0.3
    total_iters: 500
  - type: PolynomialLR
    power: 0.9

loss:
  type: BlobLoss
  
evaluate: evaluate  # evaluate func

log_iters: 4
work_dir: work_dirs/jingban
num_workers: 4
rebalance_epoch: 20
use_finetune: false
use_weightsampler: false

resume: #work_dirs/jingban/model/best.pth
class_names: 
  - background
  - jingban